name: "Publish Docker Image"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # - name: Build Image
      #   run: docker build -t kyokley/nixvim .
      # - name: Publish
      #   run: docker push kyokley/nixvim

      - name: Build Image
        run: nix build
      - name: Load Image
        run: docker load < result
      # - name: Publish
      #   run: docker push kyokley/nixvim
